### ISSUE TITLE
feature request: reproducability

### ISSUE THREAD

**Issue by sueszli** [ebanalyse/ebnerd-benchmark#6]
none of the notebook outputs / results are reproducible.

it's unclear:

- where data is being read from: all `.parquet` files are read from an absolute `/download` path.
- which files were downloaded from the many links provided by the competition organizers.

additionally this project doesn't run on windows machines because of how paths are handled through strings instead of the pathlib library. a docker container could also help resolve this issue.

---

i wrote a small shell script a while back, that could help: https://github.com/sueszli/github-lfs-bypass

alternatively we could add some clarifications in the `README`.

---

it would mean a lot if this request were to be considered.

i hope you have a nice weekend.

best,
sueszli

**Comment by johanneskruse** [comment]
Hi Sueszli,

Thank you for opening the issue and for your suggestions.

In the notebooks where you use the EB-NeRD, e.g., [nrms_ebnerd.ipynb](https://github.com/ebanalyse/ebnerd-benchmark/blob/main/examples/00_quick_start/nrms_ebnerd.ipynb), you'll need to change the paths accordingly. In this example, we've just created a folder called 'downloads' where I put the datasets you can download from the official website [recsys.eb.dk](https://recsys.eb.dk/#dataset).

The notebooks are essentially demos for now. We're showcasing how one could utilize some functionality to process the dataset and use a recommender to make predictions. We didn't use seeds or train on larger datasets. In the notebook example, we just use the demo dataset; hence, the results are not reproducible.

We will look into creating a more thorough notebook with reproducible results. I'll update the README.

We also welcome all contributions that one might think can be beneficial for other participants.
